<template>
    <MainLayoutVue>
        <div class="container mx-auto px-8">
            <div class="flex justify-center">
                <div class="max-w-3xl text-gray-400 text-lg">
                    <h1
                        class="text-4xl mb-5 text-center font-extrabold bg-gradient-to-b from-gray-100 to-gray-300 bg-clip-text text-transparent p-1">
                        Content Not Found</h1>
                </div>
            </div>
        </div>
    </MainLayoutVue>
</template>

<script setup>
import MainLayoutVue from '@/layout/MainLayout.vue';

</script>

<style lang="scss" scoped></style>